asd

diff --git a/nginx b/nginx
--- a/nginx
+++ b/nginx
@@ -98,3 +98,411 @@ nginx安装,两种方法
         /usr/sbin/nginx -t
     启动
         /etc/init.d/nginx start
+    停止
+        /etc/init.d/nginx stop
+    改配置文件后，平滑重启
+        /etc/init.d/nginx reload
+注：重启也可以用发信号的方式
+、      kill -HUP `cat /var/run/nginx.pid`  向master进程的PID发送信号
+
+nginx支持的信号
+    TEM,INT  快速关闭
+    QUIT   正常关闭
+    HUP   平滑重启reload,重新加载配置文件
+    USR1   重新打开日志文件，在切割日志时有用
+    USR2   平滑升级
+    WINCH   从容关闭工作woker进程（只剩主进程master)
+需要向master进程的PID发送信号
+nginx的工作模式是1个master进程+N个woker进程
+
+编译安装nginx
+    到目前为止，还未发现操作系统盘自带或者yum可以直接通过rpm包安装方法安装nginx的情况，如果大规模的安装可以定制rpm来安装
+    1、安装nginx所需的pcre库（perl兼容正则表达式），www.pcre.org,安装pcre库是为了使nginx支持http rewrite模块
+        mkdir -p ~/tools
+        cd ~/tools
+        sudo su -
+        wget ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre-8.39.tar.gz
+        tar xf pcre-8.39.tar.gz
+        echo $?
+        cd pcre-8.39.tar.gz
+        yum install gcc gcc-c++
+        ./configure
+        echo $?
+        make && make install 
+        echo $?
+        cd ../
+提示：configure时候最好使用默认路径，经测试指定路径后，安装nginx容易出错
+    
+    2、安装nginx
+        cd ~/tools
+        sudo su -
+        wget http://nginx.org/download/nginx-1.10.1.tar.gz
+        useradd nginx -M -s /sbin/nologin
+        tar xf nginx-1.10-1.tar.gz
+        cd nginx-1.10-1
+        ./configure --user=nginx --group=nginx --prefix=/usr/local/nginx-1.10.1 --with-http_stub_status_module --with-http_ssl_module
+        make && make install
+        ln -s /usr/local/nginx-1.10-1 /usr/local/nginx
+centos6.4最小化安装出错信息：
+    ./configure: error: SSL modules require the OpenSSL library.
+    You can either do not enable the modules, or install the OpenSSL library
+    into the system, or build the OpenSSL library statically from the source
+    with nginx by using --with-openssl=<path> option.
+            解决：yum install openssl openssl-devel 或者yum install openssl* -y
+            思路缺少librare  lib等库文件，一般是开发包devel没有安装导致
+提示：
+    这条ln命令意义重大，生产经验
+    安装指定版本号路径，方便查看及升级
+    软连接方便人类使用
+
+  nginx path prefix: "/usr/local/nginx-1.10.1"
+  nginx binary file: "/usr/local/nginx-1.10.1/sbin/nginx"
+  nginx modules path: "/usr/local/nginx-1.10.1/modules"
+  nginx configuration prefix: "/usr/local/nginx-1.10.1/conf"
+  nginx configuration file: "/usr/local/nginx-1.10.1/conf/nginx.conf"
+  nginx pid file: "/usr/local/nginx-1.10.1/logs/nginx.pid"
+  nginx error log file: "/usr/local/nginx-1.10.1/logs/error.log"
+  nginx http access log file: "/usr/local/nginx-1.10.1/logs/access.log"
+  nginx http client request body temporary files: "client_body_temp"
+  nginx http proxy temporary files: "proxy_temp"
+  nginx http fastcgi temporary files: "fastcgi_temp"
+  nginx http uwsgi temporary files: "uwsgi_temp"
+  nginx http scgi temporary files: "scgi_temp"
+
+nginx 直接configure也会内置大部分模块，也能跑的很好
+安装完成
+
+启动:
+    先检查启动脚本语法
+        /usr/local/nginx/sbin/nginx -t
+            [root@6.4-121 nginx-1.10.1]#/usr/local/nginx/sbin/nginx -t
+            /usr/local/nginx/sbin/nginx: error while loading shared libraries: libpcre.so.1: cannot open shared object file: No such file or directory
+        遇到以上错误（libpcre.so.1这个库文件没有在系统的库文件目录里面）  
+            解决办法,find这个库文件，加入到系统库文件目录中，或者把查找到的路径加入到/etc/ld.so.conf中
+            find / -name "libpcre.so.1"
+                [root@6.4-121 nginx-1.10.1]#find / -name "libpcre.so.1"
+                /usr/local/lib/libpcre.so.1
+                /home/dean/tools/pcre-8.39/.libs/libpcre.so.1
+            echo "/usr/local/lib/" >> /etc/ld.so.conf
+            ldconfig  (让修改生效)
+    启动ngix
+        /usr/local/nginx/sbin/nginx
+    查看
+        lsof -i tcp:80
+        netstat -lntup|grep 80
+    停止
+        /usr/local/nginx/sbin/nginx -s stop
+    重新加载配置文件
+        /usr/local/nginx/sbin/nginx -s reload  或者 kill -HUP `cat /usr/local/nginx/logs/nginx.pid`
+    
+    客户端链接ip测试
+        故障排查思想：
+        如果不能访问，进行排查
+            客户端ping ip               排除物理线路不通的情况
+            客户端telnet ip 服务端口      排除防火墙，服务端口开启
+            服务端 wget ip           模拟用户访问，排除http服务自身的问题，selinux的问题
+            服务端日志           查找其他位置错误
+
+疑难问题补充
+   1、 nginx:[emerg]getpwnam("nginx") failed  配置时制定了nginx用户，但是系统没添加
+        解决：useradd nginx -s /sbin/nologin -M
+   2、gcc gcc-c++ 没安装 make报错
+
+关于nginx模块：
+    nginx使用不同的模块来实现不同的功能，主要有2组重要的模块
+        1、nginx core modules(必需的)
+            包括
+            main
+            events
+        2、standard http modules(虽然不必须，但是缺省都会安装，不建议改动）
+            典型包括
+            core
+            access
+            fastcgi  与php沟通
+            gzip   压缩
+            log   日志
+            proxy  
+            rewrite  重写url
+            upstream 负载均衡模块
+            等等
+    提示：缺省情况下，以上两组模块都会安装,修改配置文件，主要是根据这2组模块的功能来修改模块参数
+
+nginx目录结构：
+    [root@6.4-121 nginx-1.10.1]#ll /usr/local/nginx/
+    total 36
+    drwx------. 2 nginx root 4096 Aug 23 12:11 client_body_temp
+    drwxr-xr-x. 2 root  root 4096 Aug 23 11:15 conf
+    drwx------. 2 nginx root 4096 Aug 23 12:11 fastcgi_temp
+    drwxr-xr-x. 2 root  root 4096 Aug 23 11:15 html
+    drwxr-xr-x. 2 root  root 4096 Aug 23 12:11 logs
+    drwx------. 2 nginx root 4096 Aug 23 12:11 proxy_temp
+    drwxr-xr-x. 2 root  root 4096 Aug 23 11:15 sbin
+    drwx------. 2 nginx root 4096 Aug 23 12:11 scgi_temp
+    drwx------. 2 nginx root 4096 Aug 23 12:11 uwsgi_temp
+    [root@6.4-121 nginx-1.10.1]#
+
+[root@6.4-121 nginx]#tree
+.
+├── client_body_temp-------------------------客户端body临时文件
+├── conf-------------------------------------nginx所有配置文件的目录，极其重要
+│   ├── fastcgi.conf--------------------------和php打交道修改这个配置，修改机会不多
+│   ├── fastcgi.conf.default
+│   ├── fastcgi_params----------------fastcgi参数文件
+│   ├── fastcgi_params.default
+│   ├── koi-utf
+│   ├── koi-win
+│   ├── mime.types
+│   ├── mime.types.default------------default是不带default的一个备份
+│   ├── nginx.conf-------------------主配置文件
+│   ├── nginx.conf.default
+│   ├── scgi_params
+│   ├── scgi_params.default
+│   ├── uwsgi_params
+│   ├── uwsgi_params.default
+│   └── win-utf
+├── fastcgi_temp------------------临时目录
+├── html-------------------这是编译安装时nginx的默认站点目录，类似于apache的htdocs目录
+│   ├── 50x.html-----------错误页面优雅替代显示文件，通过error_page 配置
+│   └── index.html---------默认的首页文件
+├── logs-----------默认log目录。包括错误日志及访问日志
+│   ├── access.log ----访问日志
+│   ├── error.log------错误日志
+│   └── nginx.pid-------nginx进程号的文件
+├── proxy_temp
+├── sbin
+│   └── nginx---------nginx启动文件
+├── scgi_temp
+└── uwsgi_temp
+
+9 directories, 21 files
+[root@6.4-121 nginx]#
+
+nginx主配置文件nginx.conf
+    整个配置文件以块的形式组织，每个块一般以一个{}来表示，块可以分几个层次，整个配置文件中Main指令位于最高层，在Main层下面有Events、HTTP等层级，而在HTTP层中又包含Server层，及server block,server block中又可分为location层，并且一个server block中可以包含多个location block
+    [root@6.4-121 conf]#grep -vE '#|^$' nginx.conf|cat -n
+     1  worker_processes  1;-------------worker的进程数量，相当于饭点服务员的数量，一般配置成和cpu的核数相当或者核数乘以2,一般8到16
+     2  events {-----------------------------------events区块
+     3      worker_connections  1024;-------------最多允许一段时间内同时链接的最大的连接数
+     4  }
+     5  http {---------------------------http区块
+     6      include       mime.types;--------全局参数
+     7      default_type  application/octet-stream;----全局参数
+     8      sendfile        on;------全局参数
+     9      keepalive_timeout  65;-----全局参数
+    10      server {-----------------------一个虚拟主机的配置
+    11          listen       80;-------监听端口
+    12          server_name  localhost;-----标识server 用ip 域名等
+    13          location / {---------------------重定向
+    14              root   html;-------------默认根目录
+    15              index  index.html index.htm;------首页文件
+    16          }
+    17          error_page   500 502 503 504  /50x.html;-------------错误代码都重定向到50x.html错误页面优雅显示，50x.html是自己设计的
+    18          location = /50x.html {----------------定义了50x.html的物理目录，可修改
+    19              root   html;
+    20          }
+    21      }
+    22  }
+    [root@6.4-121 conf]#
+
+nginx其他配置文件
+    nginx软件还会用到扩展的fastcgi相关配置文件，是通过nginx.conf主配置文件中嵌入Include命令实现的，不过默认情况是注释状态
+    fastcgi.conf
+
+        [root@6.4-121 conf]#cat fastcgi.conf
+
+        fastcgi_param  SCRIPT_FILENAME    $document_root$fastcgi_script_name;
+        fastcgi_param  QUERY_STRING       $query_string;
+        fastcgi_param  REQUEST_METHOD     $request_method;
+        fastcgi_param  CONTENT_TYPE       $content_type;
+        fastcgi_param  CONTENT_LENGTH     $content_length;
+        
+        fastcgi_param  SCRIPT_NAME        $fastcgi_script_name;
+        fastcgi_param  REQUEST_URI        $request_uri;
+        fastcgi_param  DOCUMENT_URI       $document_uri;
+        fastcgi_param  DOCUMENT_ROOT      $document_root;
+        fastcgi_param  SERVER_PROTOCOL    $server_protocol;
+        fastcgi_param  REQUEST_SCHEME     $scheme;
+        fastcgi_param  HTTPS              $https if_not_empty;
+        
+        fastcgi_param  GATEWAY_INTERFACE  CGI/1.1;
+        fastcgi_param  SERVER_SOFTWARE    nginx/$nginx_version;
+        
+        fastcgi_param  REMOTE_ADDR        $remote_addr;
+        fastcgi_param  REMOTE_PORT        $remote_port;
+        fastcgi_param  SERVER_ADDR        $server_addr;
+        fastcgi_param  SERVER_PORT        $server_port;
+        fastcgi_param  SERVER_NAME        $server_name;
+        
+        # PHP only, required if PHP was built with --enable-force-cgi-redirect
+        fastcgi_param  REDIRECT_STATUS    200;
+        [root@6.4-121 conf]#
+
+vimdiff 比较两文件重复的命令
+diff  也是比较两文件重复的命令
+    fastcgi_params
+        [root@6.4-121 conf]#diff fastcgi_params fastcgi.conf
+        1a2
+        > fastcgi_param  SCRIPT_FILENAME    $document_root$fastcgi_script_name;
+
+配置nginx虚拟主机
+    虚拟主机分类
+        基于域名   最重要
+        基于端口   次重要
+        基于ip    不重要
+
+基于域名
+    http {
+    include       mime.types;
+    default_type  application/octet-stream;
+    sendfile        on;
+    keepalive_timeout  65;
+    server {
+        listen       80;
+        server_name  www.eee.com eee.com;
+        location / {
+            root   html/www;
+            index  index.html index.htm;
+        }
+        error_page   500 502 503 504  /50x.html;
+        location = /50x.html {
+            root   html;
+        }
+    }
+}
+
+#www_eee_com
+    server {
+        listen       80;
+        server_name  www.eee.com eee.com;
+        location / {
+            root   html/www;
+            index  index.html index.htm;
+        }
+        error_page   500 502 503 504  /50x.html;
+        location = /50x.html {
+            root   html;
+        }
+    }
+#www_eee2_com
+    server {
+        listen       80;
+        server_name  www.eee2.com eee2.com;
+        location / {
+            root   html/www2;
+            index  index.html index.htm;
+        }
+        error_page   500 502 503 504  /50x.html;
+        location = /50x.html {
+            root   html;
+        }
+    }
+}
+
+上述文件创建了两个基于域名的虚拟主机，同时ip也可以访问，如果想禁止ip访问，可以创建一个空的server虚拟主机，然后重定向到其他server
+#ip
+    server {
+        listen       80;
+        server_name  127.0.0.1 localhost;
+        location / {
+            root   html/www2;
+            index  index.html index.htm;
+        }
+        error_page   500 502 503 504  /50x.html;
+        location = /50x.html {
+            root   html;
+        }
+    }
+#www_eee_com
+    server {
+        listen       80;
+        server_name  www.eee.com eee.com;
+        location / {
+            root   html/www;
+            index  index.html index.htm;
+        }
+        error_page   500 502 503 504  /50x.html;
+        location = /50x.html {
+            root   html;
+        }
+    }
+#www_eee2_com
+    server {
+        listen       80;
+        server_name  www.eee2.com eee2.com;
+        location / {
+            root   html/www2;
+            index  index.html index.htm;
+        }
+        error_page   500 502 503 504  /50x.html;
+        location = /50x.html {
+            root   html;
+        }
+    }
+}
+    
+基于端口的虚拟主机
+#www_eee_com
+    server {
+        listen       8000;
+        server_name  www.eee.com eee.com;
+        location / {
+            root   html/www;
+            index  index.html index.htm;
+        }
+        error_page   500 502 503 504  /50x.html;
+        location = /50x.html {
+            root   html;
+        }
+    }
+
+基于ip的
+linux 命令行增加ip
+ifconfig eth0:0 192.168.1.128/24 up  重启失效，永久生效需要写入配置文件 /etc/sysconfig/network-script/ifcfg_eth0:0
+
+回顾配置虚拟主机流程
+    复制server标签段，注意放在http的结束大括号前
+    更改server_name及对应网页的根目录
+    检查语法，重启服务
+    创建server_name对应的网页的根目录，并且建立测试文件
+    在客户端对server_name 的主机做host解析或dns配置，并检查
+    浏览器访问测试
+
+为虚拟主机增加日志配置
+    1、先配置error_log
+    worker_processes  8;----位置
+    error_log /tmp/logs/err.log  crit;------这项是
+    events {-----位置
+日志项的官方文档
+    http://nginx.org/en/docs/ngx_core_module.html#error_log
+    2、还可以配置events,看官方文档
+    http://nginx.org/en/docs/ngx_core_module.html#events
+        worker_processes  8;
+        error_log /tmp/logs/err.log  crit;
+        events {
+            worker_connections  1024;
+            use epoll;---------------使用epoll模式
+        }
+    3、log_format,这个格式默认的在nginx.conf.default里面，copy到nginx.conf
+        文档 http://nginx.org/en/docs/http/ngx_http_log_module.html#log_format
+        放在http块中
+            http {
+                include       mime.types;
+                default_type  application/octet-stream;
+            
+                #log_format combined '$remote_addr - $remote_user [$time_local] "$request" '
+                #                  '$status $body_bytes_sent "$http_referer" '
+                #                  '"$http_user_agent" "$http_x_forwarded_for"';
+
+    4、访问日志
+        http {
+            include       mime.types;
+            default_type  application/octet-stream;
+        
+            #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
+            #                  '$status $body_bytes_sent "$http_referer" '
+            #                  '"$http_user_agent" "$http_x_forwarded_for"';
+        
+            #access_log  logs/access.log  main;------main是调用log_format里的main 这两个要一至
+    http://nginx.org/en/docs/http/ngx_http_log_module.html#access_log
+
+
